{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "github-oidc-exchange.name" . }}
  labels:
    {{- include "github-oidc-exchange.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "github-oidc-exchange.selectorLabels" . | nindent 6 }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - port: 8080
          protocol: TCP
    {{- if .Values.serviceMonitor.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.metricsNamespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.metricsPodSelector | nindent 14 }}
      ports:
        - port: 8080
          protocol: TCP
    {{- end }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dnsNamespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dnsPodSelector | nindent 14 }}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
{{- end }}

