apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-oidc-exchange.name" . }}
  labels:
    {{- include "github-oidc-exchange.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "github-oidc-exchange.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.workloadExchange.enabled }}
    - name: workload-https
      port: 8443
      targetPort: workload-https
      protocol: TCP
    {{- end }}
